trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  # Ajustado para os nomes exatos das suas pastas
  angularProjectDir: '$(System.DefaultWorkingDirectory)/frontend'
  netProjectDir: '$(System.DefaultWorkingDirectory)/backend'
  dotnetVersion: '10.0.x'

stages:
- stage: Build_Angular
  displayName: 'Build Angular Application'
  jobs:
  - job: BuildClient
    displayName: 'npm install and build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        cd $(angularProjectDir)
        
        # Evita a quebra do pipeline se o package-lock.json não foi enviado ao Git
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
        
        npm run build -- --configuration production
      displayName: 'Angular 17 Build'

    - publish: $(angularProjectDir)/dist/browser
      artifact: 'angular-dist'
      displayName: 'Publish Angular Artifacts'

- stage: Build_DotNet
  displayName: 'Build and Publish .NET API'
  jobs:
  - job: BuildAPI
    displayName: 'dotnet build and publish'
    steps:
    - task: UseDotNet@2
      inputs:
        version: '$(dotnetVersion)'
        packageType: 'sdk'
      displayName: 'Install .NET SDK'

    - script: |
        cd $(netProjectDir)
        dotnet restore
        dotnet build --configuration $(buildConfiguration)
        dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/ApiPublish
      displayName: '.NET 10 Build and Publish'

    - publish: $(Build.ArtifactStagingDirectory)/ApiPublish
      artifact: 'dotnet-api'
      displayName: 'Publish .NET Artifacts'
